using BuildSaathi.Application.Common.Interfaces;
using BuildSaathi.Domain.Entities;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace BuildSaathi.Infrastructure.Services;

public class ReportPdfService : IReportPdfService
{
    static ReportPdfService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] GenerateBoqPdf(BOQ boq)
    {
        return QuestPDF.Fluent.Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(30);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(x => x.FontSize(10));

                page.Header().Column(column =>
                {
                    column.Item().Text("BuildSaathi BOQ Export").SemiBold().FontSize(16);
                    column.Item().Text($"BOQ: {boq.Title}");
                    column.Item().Text($"State: {boq.State} | Category: {boq.WorkCategory}");
                    column.Item().Text($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
                });

                page.Content().Column(column =>
                {
                    column.Spacing(8);
                    column.Item().Table(table =>
                    {
                        table.ColumnsDefinition(cols =>
                        {
                            cols.RelativeColumn(3);
                            cols.RelativeColumn(1);
                            cols.RelativeColumn(1);
                            cols.RelativeColumn(1);
                            cols.RelativeColumn(1);
                        });

                        table.Header(header =>
                        {
                            header.Cell().Element(CellHeaderStyle).Text("Description");
                            header.Cell().Element(CellHeaderStyle).Text("Unit");
                            header.Cell().Element(CellHeaderStyle).Text("Qty");
                            header.Cell().Element(CellHeaderStyle).Text("Rate");
                            header.Cell().Element(CellHeaderStyle).Text("Amount");
                        });

                        foreach (var line in boq.LineItems.Where(li => !li.IsDeleted).OrderBy(li => li.SortOrder))
                        {
                            table.Cell().Element(CellStyle).Text(line.Description);
                            table.Cell().Element(CellStyle).Text(line.Unit);
                            table.Cell().Element(CellStyle).Text(line.Quantity.ToString("0.##"));
                            table.Cell().Element(CellStyle).Text(line.UnitRate.ToString("N2"));
                            table.Cell().Element(CellStyle).Text(line.Amount.ToString("N2"));
                        }
                    });

                    column.Item().AlignRight().Column(summary =>
                    {
                        summary.Item().Text($"Base Total: INR {boq.BaseTotal:N2}");
                        summary.Item().Text($"Overhead ({boq.OverheadPercent:N2}%): INR {boq.OverheadAmount:N2}");
                        summary.Item().Text($"Contingency ({boq.ContingencyPercent:N2}%): INR {boq.ContingencyAmount:N2}");
                        summary.Item().Text($"Grand Total: INR {boq.TotalEstimatedCost:N2}").SemiBold();
                    });
                });

                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by BuildSaathi");
                    x.Span(" | Page ");
                    x.CurrentPageNumber();
                    x.Span(" / ");
                    x.TotalPages();
                });
            });
        }).GeneratePdf();
    }

    public byte[] GenerateInvoicePdf(Invoice invoice, IReadOnlyCollection<Payment> payments)
    {
        return QuestPDF.Fluent.Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(30);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(x => x.FontSize(10));

                page.Header().Column(column =>
                {
                    column.Item().Text("BuildSaathi Invoice").SemiBold().FontSize(16);
                    column.Item().Text($"Invoice #: {invoice.InvoiceNumber}");
                    column.Item().Text($"Client: {invoice.ClientName}");
                    column.Item().Text($"Status: {invoice.Status}");
                    if (invoice.DueDate.HasValue)
                        column.Item().Text($"Due Date: {invoice.DueDate.Value:yyyy-MM-dd}");
                });

                page.Content().Column(column =>
                {
                    column.Spacing(10);
                    column.Item().Border(1).BorderColor(Colors.Grey.Lighten2).Padding(8).Column(details =>
                    {
                        details.Item().Text($"Invoice Amount: INR {invoice.Amount:N2}");
                        details.Item().Text($"Paid Amount: INR {invoice.PaidAmount:N2}");
                        details.Item().Text($"Balance Due: INR {invoice.BalanceDue:N2}").SemiBold();
                    });

                    column.Item().Text("Payments").SemiBold();
                    column.Item().Table(table =>
                    {
                        table.ColumnsDefinition(cols =>
                        {
                            cols.RelativeColumn(1);
                            cols.RelativeColumn(1);
                            cols.RelativeColumn(1);
                            cols.RelativeColumn(2);
                        });

                        table.Header(header =>
                        {
                            header.Cell().Element(CellHeaderStyle).Text("Date");
                            header.Cell().Element(CellHeaderStyle).Text("Amount");
                            header.Cell().Element(CellHeaderStyle).Text("Method");
                            header.Cell().Element(CellHeaderStyle).Text("Reference");
                        });

                        foreach (var payment in payments.OrderByDescending(p => p.PaidDate))
                        {
                            table.Cell().Element(CellStyle).Text(payment.PaidDate.ToString("yyyy-MM-dd"));
                            table.Cell().Element(CellStyle).Text(payment.Amount.ToString("N2"));
                            table.Cell().Element(CellStyle).Text(payment.PaymentMethod ?? "-");
                            table.Cell().Element(CellStyle).Text(payment.ReferenceNumber ?? "-");
                        }

                        if (payments.Count == 0)
                        {
                            table.Cell().ColumnSpan(4).Element(CellStyle).Text("No payments recorded yet.");
                        }
                    });
                });
            });
        }).GeneratePdf();
    }

    private static IContainer CellHeaderStyle(IContainer container) =>
        container.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingVertical(4).PaddingHorizontal(2);

    private static IContainer CellStyle(IContainer container) =>
        container.BorderBottom(1).BorderColor(Colors.Grey.Lighten4).PaddingVertical(3).PaddingHorizontal(2);
}
